teams:
  - name: lf-staff
    maintainers:
      - ryjones
    members:
      - SeanBohan
      - daniela-barbosa
      - davidwboswell
      - hartm
      - jwagantall
      - minyu66
      - thelinuxfoundation
  - name: besu-admin
    maintainers:
      - fab-10
      - garyschulte
      - macfarla
      - matkt
    members:
      - jflo
      - jframe
      - siladu
  - name: besu-contributors
    maintainers:
      - garyschulte
      - jframe
      - macfarla
  - name: besu-docs-maintainers
    maintainers:
      - bgravenorst
      - joshuafernandes
    members:
      - alexandratran
      - joaniefromtheblock
      - m4sterbunny
  - name: besu-maintainers
    maintainers:
      - fab-10
      - garyschulte
      - jframe
      - macfarla
    members:
      - Gabriel-Trintinalia
      - ahamlat
      - cdivitotawela
      - daniellehrner
      - diega
      - gfukushima
      - jflo
      - joshuafernandes
      - lu-pinto
      - lucassaldanha
      - Matilda-Clerke
      - matkt
      - matthew1001
      - mbaxter
      - pinges
      - siladu
      - usmansaleem
  - name: besu-triage
    maintainers:
      - macfarla
      - jflo
      - jframe
    members:
      - ajsutton
      - antonydenyer
      - atoulme
      - NickSneo
      - gtebrean
      - kkaur01
repositories:
  - name: besu-errorprone-checks
    teams:
      besu-admin: admin
      besu-contributors: write
      besu-docs-maintainers: read
      besu-maintainers: maintain
      besu-triage: read
    visibility: public
  - name: governance
    teams:
      lf-staff: maintain
      besu-admin: maintain
      besu-maintainers: write
    visibility: public
